### ISSUE TITLE
question: how to get testname under cursor for own script handling

### ISSUE THREAD

**Issue by matu3ba** [alepez/vim-gtest#25]
I need to inspect the output of test cases and want to redirect the output into an own chosen terminal buffer,
which is easiest to do with running the gtest command with the correct test filter.

How do I get the testname under cursor for that?

```vim
" Select and run test under cursor
function! gtest#GTestRunUnderCursor()
  call gtest#GTestUnderCursor(1)
  call gtest#GTestRun()
endfunction
```
never exposes the testname as variable.
Could you change that, so it becomes usable?

**Comment by alepez** [comment]
It has been 6 years since I wrote this code, so I may be wrong. But I guess that what you need is here:

```
" Set test case
function! gtest#GTestCase(test_case)
  let g:gtest#test_case = a:test_case
endfunction

" Set test name
function! gtest#GTestName(test_name)
  let g:gtest#test_name = a:test_name
endfunction
```

So the selected test is defined as `g:gtest#test_case` and `g:gtest#test_name`.

Let me know if it is what you need. If you feel that this useful to be added in the documentation, PRs are welcome! Thanks.
